debug: true # 是否启用调试模式
grpc_addr: "127.0.0.1:8080"

mysql: {
  addr: "root:1234@tcp(127.0.0.1:3307)/test?charset=utf8&parseTime=true&loc=Local",
  open: 20,
  idle: 10,
  life: 3600000000000, # 1hour
}

redis: {
  addr: "127.0.0.1:6379",
  pwd: "",
  db: 0,
  pool: 10,
  max_retries: 3,
}

log: {
  path: "/tmp/log/grpc/server",
  level: "debug",
}
